name: 'study-springboot-grafana-prometheus'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./src/main/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./src/main/grafana/provisioning:/etc/grafana/provisioning
      - ./src/main/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge